# Generated by Django 4.1.4 on 2022-12-09 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pincode',
            new_name='transactionId',
        ),
    ]
