# Generated by Django 4.1.4 on 2022-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_brand_products_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=150, null=True),
        ),
    ]
