# Generated by Django 4.1.4 on 2022-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
